base_config: "base.yml"

run_name: "gpu_train_test"
hardware: "gpu"
steps: 30
per_device_batch_size: 4
max_target_length: 4096
model_name: "llama2-7b"
enable_checkpointing: False
attention: "cudnn_flash_te"
remat_policy: "minimal_with_context"
use_iota_embed: True
scan_layers: False
dataset_type: "synthetic"
async_checkpointing: False