# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Model config for Qwen3-Omni-30B-A3B

# Core Architectural Parameters
decoder_block: "qwen3_moe"
base_emb_dim: 2048
base_mlp_dim: 768
base_num_query_heads: 32
base_num_kv_heads: 4
base_num_decoder_layers: 48
head_dim: 128
mlp_activations: ["silu", "linear"]
vocab_size: 152064
normalization_layer_epsilon: 1.0e-6
use_qk_norm: True

# MoE Specific Parameters
num_experts: 128
num_experts_per_tok: 8
base_moe_mlp_dim: 768
norm_topk_prob: true

# RoPE Settings
rope_max_timescale: 1_000_000
max_position_embeddings: 65536

# General Model Settings
enable_dropout: False
scan_layers: False  # deepstack does not support scan_layers

# Vision Encoder Configuration
# Based on https://github.com/huggingface/transformers/blob/main/src/transformers/models/qwen3_omni_moe/configuration_qwen3_omni_moe.py
image_size_for_vit: 768
hidden_size_for_vit: 1152
intermediate_size_for_vit: 4304
num_attention_heads_for_vit: 16
num_hidden_layers_for_vit: 27
num_channels_for_vit: 3
patch_size_for_vit: 16
temporal_patch_size_for_vit: 2
spatial_merge_size_for_vit: 2
out_hidden_size_for_vit: 2048
num_position_embeddings_for_vit: 2304
deepstack_visual_indexes_for_vit: [8, 16, 24]

use_multimodal: true
use_audio: true
# Audio Encoder Configuration (need to set use_audio=true to enable)
# Based on https://github.com/huggingface/transformers/blob/main/src/transformers/models/qwen3_omni_moe/configuration_qwen3_omni_moe.py
d_model_for_audio: 1280
encoder_layers_for_audio: 32
encoder_attention_heads_for_audio: 20
encoder_ffn_dim_for_audio: 5120
max_source_positions_for_audio: 1500
num_mel_bins_for_audio: 128
downsample_hidden_size_for_audio: 480
output_dim_for_audio: 2048
attention_dropout_for_audio: 0.0
n_window_for_audio: 50
n_window_infer_for_audio: 400
conv_chunksize_for_audio: 500
num_conv_layers_for_audio: 3
max_timescale_for_audio: 10000.0
max_sample_len_for_audio: 10000
# MRoPE Settings (Multi-dimensional RoPE for multimodal)
use_mrope: true
mrope_section: [24, 20, 20]
position_id_per_seconds: 13
